### ISSUE TITLE
Not Installable on Windows 11 VM ARM64 VM on MackBook Pro M2

### ISSUE THREAD

**Issue by mikemurphysmind** [madskristensen/OpenInVsCode#35]
I recently purchased a Mac Book Pro M2 and am running Parallels install of Windows 11 on ARM64.  Running Visual Studio 2022 Professional.  I tried to install the OpenInVSCode extension and I get the attached error.

**To Reproduce**
1. Download VSIX and run it.
2. Install fails

**Expected behavior**

**Screenshots**

![Untitled 2](https://user-images.githubusercontent.com/73149285/225449079-6fdafd94-7d4f-40f2-9d51-66d2aba201e1.png)

**Install Log**

3/15/2023 5:25:25 PM - Microsoft VSIX Installer
3/15/2023 5:25:25 PM - -------------------------------------------
3/15/2023 5:25:25 PM - vsixinstaller.exe version:
3/15/2023 5:25:25 PM - 17.5.4065+gbda5f544dc
3/15/2023 5:25:25 PM - -------------------------------------------
3/15/2023 5:25:25 PM - Command line parameters:
3/15/2023 5:25:25 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Open_in_Visual_Studio_Code_v1.4.50 (1).vsix
3/15/2023 5:25:25 PM - -------------------------------------------
3/15/2023 5:25:25 PM - Microsoft VSIX Installer
3/15/2023 5:25:25 PM - -------------------------------------------
3/15/2023 5:25:29 PM - Initializing Install...
3/15/2023 5:25:30 PM - Extension Details...
3/15/2023 5:25:30 PM - 	Identifier         : e99dde0e-e023-410d-bc5d-3f76db71e3f0
3/15/2023 5:25:30 PM - 	Name               : Open in Visual Studio Code
3/15/2023 5:25:30 PM - 	Author             : Mads Kristensen
3/15/2023 5:25:30 PM - 	Version            : 1.4.50
3/15/2023 5:25:30 PM - 	Description        : Adds a menu command that lets you open any solution, project, folder and file in Visual Studio Code.
3/15/2023 5:25:30 PM - 	Locale             : en-US
3/15/2023 5:25:30 PM - 	MoreInfoURL        : https://github.com/madskristensen/OpenInVsCode/
3/15/2023 5:25:30 PM - 	InstalledByMSI     : False
3/15/2023 5:25:30 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
3/15/2023 5:25:30 PM - 	SignatureState     : Unsigned
3/15/2023 5:25:30 PM - 	Supported Products : 
3/15/2023 5:25:30 PM - 		Microsoft.VisualStudio.Pro
3/15/2023 5:25:30 PM - 			Version : [15.0,17.0)
3/15/2023 5:25:30 PM - 			ProductArchitecture : x86
3/15/2023 5:25:30 PM - 		Microsoft.VisualStudio.Pro
3/15/2023 5:25:30 PM - 			Version : [17.0,18.0)
3/15/2023 5:25:30 PM - 			ProductArchitecture : amd64
3/15/2023 5:25:30 PM - 	References         : 
3/15/2023 5:25:30 PM - 	Prerequisites      : 
3/15/2023 5:25:30 PM - 		-------------------------------------------------------
3/15/2023 5:25:30 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/15/2023 5:25:30 PM - 		Name         : Visual Studio core editor
3/15/2023 5:25:30 PM - 		Version      : [15.0,)
3/15/2023 5:25:30 PM - Signature Details...
3/15/2023 5:25:30 PM - 	Extension is not signed.
3/15/2023 5:25:30 PM - Searching for applicable products...
3/15/2023 5:25:30 PM - Found installed product - Visual Studio Professional 2022
3/15/2023 5:25:30 PM - Found installed product - Global Location
3/15/2023 5:25:30 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

 **Visual Studio Info** 

Microsoft Visual Studio Professional 2022
Version 17.5.2
VisualStudio.17.Release/17.5.2+33502.453
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.50105.3 Commit Hash:882de61a7c99ae988d4c62029301292a3e0b1d56
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.5.2.2312702+323f505b8fab392bd096ccc384321ca7f26f2633
Provides languages services for ASP.NET Core Razor.

Redgate SQL Prompt   1.0.0.0
Write, format, and refactor SQL effortlessly

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23128.14+651d32d8017cfcc60fcbd67383601fa9a3deb145
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Device Info**

Device name	MURPHYSMIND001
Processor	Apple Silicon   3.20 GHz  (4 processors)
Installed RAM	8.00 GB
Device ID	6BDBDEA9-7B6C-4D65-BC32-6EA6B9205A2E
Product ID	00330-80144-55340-AA669
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen support

**Windows Info**

Edition	Windows 11 Pro
Version	22H2
Installed on	‎3/‎14/‎2023
OS build	22621.525
Experience	Windows Feature Experience Pack 1000.22634.1000.0

**Comment by mikemurphysmind** [comment]
I pulled down the project and debugged it VS 2022 on my Windows 11 ARM64 VM.   It ran with no issues.   I am wondering if the issue is with Visual Studio Extension manager installation and not the Extension itself.

**Comment by sitefinitysteve** [comment]
I hit this today as well, I didn't see the extension in the store, so tried downloading and running from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpeninVisualStudioCode and I get the same error as above.

This is such a great extension, used daily on my old Intel box
